Add terminology section. Fixes #12.
w3c/did-use-cases pull request #33
Opened 2019-11-06 09:06 UTC by peacekeeper

2019-11-06 21:05 UTC, jandrieu requested changes
Still needs some work, but we'd like to get it into FPWD if we can make the adjustments.

2019-11-06 21:05 UTC, jandrieu commented on terms.html
> +A definition of how a specific <a>DID scheme</a> can be implemented
This definition isn't quite right. the "DID scheme" is "did", the DID method is something different, which I believe is specified within the DID as the method-string.

2019-11-06 21:05 UTC, jandrieu commented on terms.html
> +method(s) by which <a>DIDs</a> are resolved and deactivated and <a>DID
We should avoid using "method" with a subtly different meaning within the definition of a DID Method. Perhaps "mechanisms by which one resolves and interacts with DIDs and DID Documents".

2019-11-06 21:05 UTC, jandrieu commented on index.html
> +        <h1>Terminology</h1>
This section should be flagged as under discussion, referencing https://github.com/w3c/did-core/issues/4 at a minimum. There's a way in ReSpec to do that automagically.

2019-11-06 21:05 UTC, jandrieu commented on terms.html
> +[[DID-RESOLUTION]].
We need to figure out how to reference external documents like this. A concern was raised that this reads as if the DID Resolution specification is already completed work, while this document should be informing that work. If we define resolver simply based on the function of retrieving a DID Document, that would probably solve the concern.

2019-11-07 06:32 UTC, peacekeeper commented
@jandrieu Good feedback, but note that I simply copied the terms from the did-core spec:
https://github.com/w3c/did-core/blob/master/terms.html

Are you proposing to make those changes there as well?

2019-11-12 05:19 UTC, jandrieu commented
I would. Some of those are fundamentally wrong... like referring to the did method as the schema.

2019-11-12 08:23 UTC, tplooker commented on terms.html
> +registered with <a>distributed ledger technology</a> (DLT) or other form of
Do we want to rephrase that anchoring a DID to a distributed ledger is optional, for example did:key did:nacl did:peer are more of ledger did's?

2019-11-12 18:04 UTC, philarcher commented
I believe everything in this PR has now been included in the current draft (see https://w3c.github.io/did-use-cases/#concepts-of-decentralized-identity). This addition has been flagged in various places as highlighted in this commentary and in the WG. I would therefore like to close this PR *without* merging it.

2019-11-14 04:57 UTC, jandrieu commented
@peacekeeper Let us know if we can close this out. I think the approach we discussed on Tuesday is pulled into the FPWD.

If there's still some edits you'd like, we should probably do it in a separate PR.

2019-12-04 21:11 UTC, jandrieu commented
Closing this as the FPWD has overtaken this PR with good consensus from the WG.

2019-12-04 21:11 UTC, closed without merging