Added three new short UCs
w3c/did-use-cases pull request #65
Opened 2020-01-23 12:12 UTC by philarcher

These need review and are likely to be improved (I sure hope so!)

2020-01-23 14:34 UTC, msporny requested changes
Overall, LGTM. We need to be consistent about marking up terminology such as "decentralized identifier" and "verifiable credential" and linking it back to the shared glossary via the use of ReSpec &lt;a&gt; autolinking tags. My assumption is that the editors are going to go through the document and fix this up at a later date.

2020-01-23 14:34 UTC, msporny commented on index.html
> +		verificable credentials associated with that identifier.</li>
```suggestion
		verifiable credentials associated with that identifier.</li>
```

2020-01-26 18:31 UTC, OR13 commented
Thanks for doing this. These use cases are really helpful. Other than the spelling, looks good.

2020-01-30 13:13 UTC, jandrieu approved these changes

2020-01-30 13:13 UTC, merged